/*
Digital Value Services API

Testing OperatorsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package dvsapi

import (
	"context"
	openapiclient "github.com/josnidhin/go-openapi-codegen-examples/dvsclient/dvsapi"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_dvsapi_OperatorsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OperatorsApiService GetOperatorById", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var operatorId int32

		resp, httpRes, err := apiClient.OperatorsApi.GetOperatorById(context.Background(), operatorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperatorsApiService GetOperators", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.OperatorsApi.GetOperators(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
