/*
Digital Value Services API

Testing PromotionsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package dvsapi

import (
	"context"
	openapiclient "github.com/josnidhin/go-openapi-codegen-examples/dvsclient/dvsapi"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_dvsapi_PromotionsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PromotionsApiService GetPromotionById", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var promotionId int32

		resp, httpRes, err := apiClient.PromotionsApi.GetPromotionById(context.Background(), promotionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PromotionsApiService GetPromotions", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.PromotionsApi.GetPromotions(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
